[binaries]
# Use vcpkg's pkg-config if available
pkgconfig = ['pkg-config']
c = 'i686-w64-mingw32-gcc'
cpp = 'i686-w64-mingw32-g++'
ar = 'i686-w64-mingw32-ar'
windres = 'i686-w64-mingw32-windres'
strip = 'i686-w64-mingw32-strip'

[built-in options]
# Use vcpkg environment variables for pkg-config paths
